#spring:
#  config:
#    import: optional:configserver:http://localhost:5001
#  profiles:
#    active:apigateway




#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: USER-SERVICE
#        uri: lb://USER-SERVICE
#        predicates:
#        - Path=/user/**
        
#      - id: HOTAL-SERVICE
#        uri: lb://HOTAL-SERVICE
#        predicates:
#        - Path=/hotel/**
        # for all urls
        #- Path=/**
        # multipule urls for specific controlers
        #- Path=/hotel/**,/staffe/**
        
#      - id: RATING-SERVICE
#        uri: lb://RATING-SERVICE
#        predicates:
#        - Path=/rating/**